config/routes.rb
Rails.application.routes.draw do
 resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  
  
=begin
  def display_name
    "#{title}(#{author})"
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book,only:[:show, :edit, :update, :destroy]
  def index 
    @books=Book.all
  end
    
  def show
   @book=Book.find_by(id: params[:id])
  end
  
  def new
    @book=Book.new
  end

  
  def create
    @book = Book.new(book_params)
    if @book.save
       redirect_to books_path
    else
      render 'new'
    end  
  end
  
  def edit
  end
  
  def update
 
    if @book.update(book_params)
      redirect_to books_path, notice:"update!"
    else
    render 'edit'
    end
  end
  
  private
    def find_book
      @book = Book.find_by(id: params[:id])
      redirect_to books_path, notice:"no data!" if @book.nil?
    end
  
    def book_params
      params.require("book").permit(:title, :intro, :author, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for book do |f| %>

書名: <%= f.text_field :title %><br />
簡介: <%= f.text_area :intro %><br />
作者名稱: <%= f.text_field :author %><br />
售價: <%= f.text_field :price %><br />

<%=f.submit %>

<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<h1>Book</h1>
<%= link_to "add book", new_book_path(@book) ,class: "btn btn-primary"%>
<table class= "table table-hover ">

  <thead>
  <tr>
    <td>書名</td>
    <td>簡介</td>
    <td>作者姓名</td>
    <td>售價</td>
  </tr>
  </thead>
  
   <tbody>
      <% @books.each do |book| %>
      <tr>
        <td><%= book.title %>
        <td><%= book.intro %></td>
        <td><%= book.author %></td>
        <td><%= book.price %></td>
        <td>
          <%= link_to "編輯", edit_book_path(book) "btn btn-success btn-xs"%>
          <%= link_to "刪除", book_path(book), method: "delete", data: { confirm: "確認刪除" } "btn btn-danger btn-xs"%>
        </td>
      </tr> 
   </tbody>
<% end %>
 </table>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' , book: @book %>

app/views/books/show.html.erb
<h1>
  <%= @book.name %>
</h1>
<%= @book.title %> <br/>
<%= link_to "back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>